## Paste here token returned by login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkb3MiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AdGZtLmVzIiwiZXhwIjoxNjk3MzgxNzc3LCJpZCI6MSwibm9tYnJlIjoiQWRtaW4iLCJyZXN0YXVyYWRvciI6dHJ1ZX0.2vKa_Ry7ELri94fJPe0UNA1lBeC2vV2X4eIAR0-ATXw
@userid = 1
@carritoid = 2

### Carritos Details (requires login)
GET http://localhost:8080/carritos/
Authorization: Bearer {{token}}
Content-Type: application/json



### Carritos Save (requires login)
POST http://localhost:8080/carritos/
Authorization: Bearer {{token}}
Content-Type: application/json

{ "carritoLineas": [ { "platoId": 1, "cantidad": 2 }] }


### Carritos Delete (requires login)
DELETE http://localhost:8080/carritos/
Authorization: Bearer {{token}}
Content-Type: application/json
