## Paste here token returned by login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkb3MiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AdGZtLmVzIiwiZXhwIjoxNjk3MzgxNzc3LCJpZCI6MSwibm9tYnJlIjoiQWRtaW4iLCJyZXN0YXVyYWRvciI6dHJ1ZX0.2vKa_Ry7ELri94fJPe0UNA1lBeC2vV2X4eIAR0-ATXw
@orderid = 1


### Orders Create From Cart (requires login and cart content)
POST http://localhost:8080/order/
Authorization: Bearer {{token}}
Content-Type: application/json


### Orders List
GET http://localhost:8080/orders/?day=2023-10-15
Authorization: Bearer {{token}}
Content-Type: application/json


### Orders Delete (requires login)
DELETE http://localhost:8080/order/{{orderid}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Orders Details
GET http://localhost:8080/order/{{orderid}}
Authorization: Bearer {{token}}
Content-Type: application/json


@lineid = 1

### Orders Modify Line - Existing (requires login)
PATCH http://localhost:8080/order/{{orderid}}/line/{{lineid}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ "quantity": 2 }


### Orders Modify Line - New (requires login)
POST http://localhost:8080/order/{{orderid}}/line/
Authorization: Bearer {{token}}
Content-Type: application/json

{ "dishId": 2, "quantity": 1 }