## Paste here token returned by login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkb3MiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AdGZtLmVzIiwiZXhwIjoxNjk3MzgxNzc3LCJpZCI6MSwibm9tYnJlIjoiQWRtaW4iLCJyZXN0YXVyYWRvciI6dHJ1ZX0.2vKa_Ry7ELri94fJPe0UNA1lBeC2vV2X4eIAR0-ATXw
@promotionid = 1
@dishid = 1

### Promotions Create (requires login)
POST http://localhost:8080/promotion/
Authorization: Bearer {{token}}
Content-Type: application/json

{ "dishId": {{dishid}}, "startTime": "2023-01-01T00:00:00+01:00", "endTime": "2023-12-12T00:00:00+01:00", "cost": 5.50  }


### Promotions List
GET http://localhost:8080/promotions?limit=10&page=1
Content-Type: application/json


### Promotions Delete (requires login)
DELETE http://localhost:8080/promotion/{{promotionid}}
Authorization: Bearer {{token}}
Content-Type: application/json


### Promotions Details
GET http://localhost:8080/promotion/{{promotionid}}
Content-Type: application/json



### Promotions Modify (requires login)
PATCH http://localhost:8080/promotion/{{promotionid}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ "dishId": {{dishid}}, "startTime": "2023-01-01T00:00:00+01:00", "endTime": "2023-12-12T00:00:00+01:00", "cost": 4.50 }