## Paste here token returned by login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGVsbGlkb3MiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AdGZtLmVzIiwiZXhwIjoxNjk3MjE5ODM3LCJpZCI6MCwibm9tYnJlIjoiQWRtaW4iLCJyZXN0YXVyYWRvciI6dHJ1ZX0.fTafymPVZTrb7JtPzYTI3P8UcEfNK1FgYQVKsqHzOok
@userid = 2

### Usuario Create
POST http://localhost:8080/usuarios/
Content-Type: application/json

{ "email": "user1@tfm.es", "password": "password", "nombre": "Usuario 1", "apellidos": "Apellido1 Apellido2", "direccion1": "Calle del Percebe", "direccion2": "Numero 5 Piso 2", "ciudad": "Madrid", "codigoPostal": "12345", "telefono": "987376767218" }


### Usuario Delete
DELETE http://localhost:8080/usuarios/{{userid}}
Authorization: Bearer {{token}}
Content-Type: application/json



### Usuario Get (requires login)
GET http://localhost:8080/usuarios/{{userid}}
Authorization: Bearer {{token}}
Content-Type: application/json



### Usuario Modificar (requires login)
PATCH http://localhost:8080/usuarios/{{userid}}
Authorization: Bearer {{token}}
Content-Type: application/json

{ "id": {{userid}}, "password": "password", "telefono": "187376767218" }

