CREATE DATABASE tfm;
CREATE USER tfm WITH PASSWORD 'password';
GRANT CONNECT ON DATABASE tfm TO tfm;
\connect tfm
DROP SCHEMA IF EXISTS tfm;
CREATE SCHEMA tfm;
ALTER SCHEMA tfm OWNER TO tfm;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

